<form action="index.php" method="post">
  <label for="firstName">Prénom</label>
  <input type="text" id="firstName" name="firstName">

  <label for="lastName">Nom</label>
  <input type="text" id="lastName" name="lastName">

  <label for="email">Email</label>
  <input type="email" id="email" name="email">

  <label for="password">Mot de passe</label>
  <input type="password" id="password" name="password">

  <label for="confirmPassword">Confirmation du mot de passe</label>
  <input type="password" id="confirmPassword" name="confirmPassword">

  <input type="hidden" name="formName" value="register">

  <input type="submit" value="Créer un compte">
</form>