<!DOCTYPE html>  
<html lang="fr">  
    <head>        
        <meta charset="utf-8">  
        <title>Le titre de ma page</title>  
        <!--<link rel="stylesheet" href="assets/styles/css/style.css" />  -->
        
        <script src="https://kit.fontawesome.com/dbf8b52bf4.js" crossorigin="anonymous"></script>
    </head>    
    <body>        
    <?php
    require "partials/_header.phtml";

    require $template."/".$template.".phtml";

    require "partials/_footer.phtml";
    ?>    
    </body>
</html>